application: coverchat
version: 2
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 365d

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: app.app

inbound_services:
- warmup
